- alias: "Nobody Home"
  trigger:
    - platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
      for:
        minutes: 30
  action:
    service: script.turn_on
    entity_id: script.nobody_home